ci:
  skip:
    - cargo-fmt
    - cargo-clippy

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: https://github.com/kykosic/pre-commit-rust
    rev: '0.4.0'
    hooks:
      - id: cargo-fmt
      - id: cargo-clippy
