[package]
name = 'document_tree'
version = '0.3.0'
authors = ['Philipp A. <flying-sheep@web.de>']
description = 'reStructuredText’s DocumenTree representation'
license = 'MIT OR Apache-2.0'

documentation = 'https://flying-sheep.github.io/rust-rst'
homepage = 'https://github.com/flying-sheep/rust-rst'
repository = 'https://github.com/flying-sheep/rust-rst.git'

edition = '2018'

[dependencies]
failure = '0.1.6'
regex = '1.3.1'
url = '2.1.0'
serde = '1.0.104'
serde_derive = '1.0.104'
