name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build, check, and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,just
    - uses: Swatinem/rust-cache@v2
    - run: just build
    - run: just check
    #- run: just fmt --check
    - run: just test
